{% set name = "cplot" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cplot-{{ version }}.tar.gz
  sha256: 5534dcb977ac01238be9633d2f3bf0e6079b8c56b3923c643648609421cb10d0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - matplotx >=0.3.10
    - npx
    - numpy >=1.20.0

test:
  imports:
    - cplot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/cplot/
  summary: Plot complex-valued functions
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
